/* --- The following code comes from c:\lcc\lib\wizard\stddef.tpl. */
// This are the definitions for all symbols used in menus or string.
#define IDACCEL 10000
#define IDM_RECONNECT 270
#define IDM_EXIT 300
#define IDM_ABOUT 500
#define IDMAINMENU 600
#define IDAPPLICON 710
#define IDAPPLCURSOR 810
#define IDS_FILEMENU 2000
#define IDS_HELPMENU 2010
#define IDS_SYSMENU 2030
#define IDM_STATUSBAR 3000
#define IDC_TEXTBOX_EEDUMP 201
#define IDC_TEXTBOX_IOPDUMP 202
#define IDC_TEXTBOX_EEDUMPSTART 203
#define IDC_TEXTBOX_EEDUMPEND 204
#define IDC_TEXTBOX_IOPDUMPSTART 205
#define IDC_TEXTBOX_IOPDUMPEND 206
#define IDC_TEXTBOX_KERNELDUMP 207
#define IDC_TEXTBOX_SCRATCHPADDUMP 208
#define IDC_TEXTBOX_KERNELDUMPSTART 209
#define IDC_TEXTBOX_KERNELDUMPEND 211
#define IDC_TEXTBOX_SCRATCHPADDUMPSTART 212
#define IDC_TEXTBOX_SCRATCHPADDUMPEND 213
#define IDC_LABEL_EEDUMP 301
#define IDC_LABEL_IOPDUMP 302
#define IDC_LABEL_EEDUMPSTART 303
#define IDC_LABEL_EEDUMPEND 304
#define IDC_LABEL_IOPDUMPSTART 305
#define IDC_LABEL_IOPDUMPEND 306
#define IDC_LABEL_KERNELDUMP 307
#define IDC_LABEL_SCRATCHPADDUMP 308
#define IDC_LABEL_KERNELDUMPSTART 309
#define IDC_LABEL_KERNELDUMPEND 310
#define IDC_LABEL_SCRATCHPADDUMPSTART 311
#define IDC_LABEL_SCRATCHPADDUMPEND 312
#define IDC_LABEL_DUMPSTATE 313
#define IDC_PROGRESSBAR_DUMPSTATE 400
#define IDC_BUTTON_EEDUMP 501
#define IDC_BUTTON_IOPDUMP 502
#define IDC_BUTTON_KERNELDUMP 503
#define IDC_BUTTON_SCRATCHPADDUMP 504
#define IDC_BUTTON_HALTRESUME 505
#define IDMAINICON 100


