/* --- The following code comes from c:\lcc\lib\wizard\stddef.tpl. */
// This are the definitions for all symbols used in menus or string.
#define IDACCEL 10000
#define IDM_NEW 200
#define IDM_OPEN 210
#define IDM_SAVE 220
#define IDM_SAVEAS 230
#define IDM_CLOSE 240
#define IDM_PRINT 250
#define IDM_PAGESETUP 260
#define IDM_EXIT 300
#define IDM_ABOUT 500
#define IDMAINMENU 600
#define IDAPPLICON 710
#define IDAPPLCURSOR 810
#define IDS_FILEMENU 2000
#define IDS_HELPMENU 2010
#define IDS_SYSMENU 2030
#define IDM_STATUSBAR 3000
#define IDC_TEXTBOX_EEDUMP 201
#define IDC_TEXTBOX_IOPDUMP 202
#define IDC_TEXTBOX_EEDUMPSTART 203
#define IDC_TEXTBOX_EEDUMPEND 204
#define IDC_TEXTBOX_IOPDUMPSTART 205
#define IDC_TEXTBOX_IOPDUMPEND 206
#define IDC_LABEL_EEDUMP 301
#define IDC_LABEL_IOPDUMP 302
#define IDC_LABEL_EEDUMPSTART 303
#define IDC_LABEL_EEDUMPEND 304
#define IDC_LABEL_IOPDUMPSTART 305
#define IDC_LABEL_IOPDUMPEND 306
#define IDC_PROGRESSBAR_EEDUMPSTATE 401
#define IDC_PROGRESSBAR_IOPDUMPSTATE 402
#define IDMAINICON 100

